### ISSUE TITLE
Changes on BGG are not applied

### ISSUE THREAD

**Issue by simonlinden82** [EmilStenstrom/mybgg#11]
This may be an error on my behalf but I set up my site first and then updated my BGG-account. But these changes don't show on the active mybgg page. How do I update it with the latest changes from bgg?

**Comment by simonlinden82** [comment]
Ok thanks! It works after running that command.
I have just followed your instructions without really knowing what I did. But since I don't have to push any changes after running that command I assume it just sends the information from bgg to algiola and doesn't store anything on my drive. I didn't understand this the first time I went through your instructions.

I have to say I really like the ability to compare my games the way this site lets me do. Thanks for sharing it:)

**Comment by EmilStenstrom** [comment]
Happy you got it working! :)

You are exactly right, the command downloads the games from BGG, and uploads them to Algolia. The site sends search queries to algolia.
