### ISSUE TITLE
Can't seem to import above 99 games

### ISSUE THREAD

**Issue by lajlev** [EmilStenstrom/mybgg#13]
It should fetch 116 games
Profile  https://boardgamegeek.com/user/kinkymachine
Repo https://github.com/lajlev/kinkymachine/tree/master

```
Imported 99 games from boardgamegeek.
Indexed 99 games in algolia, and removed everything else.
```

**Comment by lajlev** [comment]
Sorry to keep finding minor bugs 🐛

**Comment by EmilStenstrom** [comment]
That's actually correct. 99 games = 116 games - 17 expansions. Expansions are grouped together with the main game, you get to them by expanding each game.

**Comment by lajlev** [comment]
Great

________________________________

**Comment by EmilStenstrom** [comment]
Updated the printout so it includes the number of expansions separately. This should make sure this gets less confusing I think.
