### ISSUE TITLE
error fetching BGG API response: non-XML reply

### ISSUE THREAD

**Issue by lajlev** [EmilStenstrom/mybgg#14]
When I tried use it for a boardgame cafe in copenhagen https://boardgamegeek.com/user/BastardCafe

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/boardgamegeek/utils.py", line 337, in request_and_parse_xml
    raise BGGApiError("non-XML reply")
boardgamegeek.exceptions.BGGApiError: non-XML reply

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download_and_index.py", line 296, in <module>
    main(args)
  File "download_and_index.py", line 254, in main
    extra_params=SETTINGS["boardgamegeek"]["extra_params"],
  File "download_and_index.py", line 108, in collection
    [game_in_collection.id for game_in_collection in collection]
  File "/usr/local/lib/python3.6/site-packages/boardgamegeek/api.py", line 797, in game_list
    retry_delay=self._retry_delay)
  File "/usr/local/lib/python3.6/site-packages/boardgamegeek/utils.py", line 367, in request_and_parse_xml
    raise BGGApiError("error fetching BGG API response: {}".format(e))
boardgamegeek.exceptions.BGGApiError: error fetching BGG API response: non-XML reply
```

**Comment by EmilStenstrom** [comment]
I'm guessing this has to do with the XML response somehow becoming too big. The cafe has 2700 games (!). I'll try importing them locally and see what happens. Will report back.

**Comment by lajlev** [comment]
😱👍

________________________________

**Comment by EmilStenstrom** [comment]
Ok! I've rewritten much of the logic to parse the result from BGG. That made it possible to handle the error you got with that many games: The URL for fetching the games got too long. Now I fetch 100 games at the time. I've successfully imported BastardCafe´s collection locally, so it seems to work!

Does this mean I get free entrance to BastardCafé if I'm ever in Copenhagen?! :)

**Comment by EmilStenstrom** [comment]
Please try again with the latest version, and keep the bug reports coming!

**Comment by lajlev** [comment]
Sure

________________________________

**Comment by EmilStenstrom** [comment]
I assume think solved your problem. Please reopen this if you still see this problem.
