### ISSUE TITLE
Number of items per page

### ISSUE THREAD

**Issue by ewyll** [EmilStenstrom/mybgg#18]
Site looks weird in iPad because there is 20 items per page, and on iPad, you see just three columns. It would be better if number of items per page was 24, which is divisible by 2, 3 and 4 - which would fit for all widths.

**Comment by EmilStenstrom** [comment]
Oh, excellent suggestion. I'll have a look at fixing that when I find some spare time. I think I'll make it configurable in config.json too, so people can up it to 48 if they want to.

**Comment by EmilStenstrom** [comment]
Hi again! I've update the latest version to have 24 items as the default. The value is also configurable using [config.json](https://github.com/EmilStenstrom/mybgg/blob/master/config.json#L16). Hope you like it! :)

**Comment by ewyll** [comment]
Nice, thanks for the update! :)
