### ISSUE TITLE
Game descriptions getting truncated by a colon?

### ISSUE THREAD

**Issue by Kornstalx** [EmilStenstrom/mybgg#19]
I've noticed that every boardgame in my collection that has its description (imported directly from BGG) beginning with "Game description from the publisher:" gets the description cut off. This is only happening for those titles. There's a _lot_ of titles that have this prefix in their boardgamegeek descriptions, and they're all getting cut off.

I'm using the latest version (merged this morning) and am not sure if I've noticed this before.

Example: https://i.imgur.com/E4I7qzN.jpg

**Comment by EmilStenstrom** [comment]
Ah. The code picks the text up to the first line break. Seems I need to get smarter about how to extract a  good chunk of text from there. Thanks for the bug report.

**Comment by EmilStenstrom** [comment]
Hi again, I've added a new cleverer way to pick a paragraph from the long BGG description. Try the latest version and let me know if it works better. It removed all "Game description from the publisher:" for me at least.

The new algorithm is: "Pick the first paragraph that's longer than 80 characters".

**Comment by Kornstalx** [comment]
This works great, so much better! Thanks for the update.

On an unrelated note, I have a question: How difficult would it be to add more categories to the game filters? I often wish I had a "Publisher" filter on the right. Pretty sure this is baked into the BGG API already.

**Comment by EmilStenstrom** [comment]
Are you asking how difficult it would be for you to do it, or for me? :) I currently have no need for that, (I don't pick games based on publisher), so I guess some kind of configuration stuff would be needed, that lets different people set different filters... Currently that's quite a lot of work.
