### ISSUE TITLE
code organization suggestion

### ISSUE THREAD

**Issue by ewyll** [EmilStenstrom/mybgg#20]
This more of an suggestion than a real issue.
It would be nice if _html/web code_ is in a separate folder (say: `www`), which would make uploading to hosting of our choice easier.
Or, if you prefer supporting hosting this in people's github hosting, move the non-www code to some `/scripts` or similar folder.

In the current state, I need to guess/remember which files need to be uploaded.

Thanks ;)

**Comment by EmilStenstrom** [comment]
Great point, I'll see what I can do :)

**Comment by EmilStenstrom** [comment]
Done, I've moved the python scripts to a "scripts" directory, and kept the "www"-files in the root dir. This makes it easy to host on GitHub Pages. Also: Nothing sensitive is kept in any of the github files (including config.json), so it's safe to push all files to the hosting of your choice.
