### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by lajlev** [EmilStenstrom/mybgg#23]
Any way to set sorting of games?

I would like to set it by number of ratings. To show most attractive games first.

**Comment by lajlev** [comment]
Here is the use case https://braetspilaarhus.dk/spilleri/spilbibliotek/

**Comment by EmilStenstrom** [comment]
Oh, that’s great use of this library! Thanks for sharing.

When you say number of votes, do you mean the final geekrating?

**Comment by lajlev** [comment]
nope I think number of ratings is more relevant than geekrating.
But if numratings is hard to do then geekrating is better than alfabetic IMO

**Comment by EmilStenstrom** [comment]
Hi again! The latest version of mybgg now supports custom sorting orders by just updating config.json. I've added the documentation under https://github.com/EmilStenstrom/mybgg#getting-your-own-site-up-and-running-the-first-time - Under the `|> Details`, the "sort_by". 

After setting that, just running download_and_index again should get you the order you wanted! :)

**Comment by lajlev** [comment]
Works great 👍 

Feature idea: Set sorting in UI fx http://u.lillefar.dk/tYyohV

**Comment by lajlev** [comment]
Now live with awesome sorting. The game library is core at the festival, so you code is gonna improve the festival experience for a lot of people, in the upcoming weekend http://braetspilaarhus.dk/spilleri/spilbibliotek/

If you should want to come, I'll give a beer 🍻

**Comment by EmilStenstrom** [comment]
Wow, that looks great! I'm not planning on coming unfortunately, but thanks for the encouragement! :)
