### ISSUE TITLE
Feature request - Use version art of games owned

### ISSUE THREAD

**Issue by Medwynd** [EmilStenstrom/mybgg#24]
For example:
I own the 1999 version of Acquire but the art in the collection uses the one on the main entry

https://boardgamegeek.com/boardgame/5/acquire

**Comment by EmilStenstrom** [comment]
Thanks for reporting, I'll see what I can do.

**Comment by EmilStenstrom** [comment]
Hi again! I've now made sure the image from the selected version is used instead of the generic one, if there is a version. Hope this matches what you were looking for?

(PS. Some appreciation in the original request would be nice, this is a side project for me)

**Comment by Medwynd** [comment]
Thanks for this, they came out great.  I like how for games with smaller images you used a blurred our version of it blown up as the background.

**Comment by EmilStenstrom** [comment]
Happy you like it! :)
