### ISSUE TITLE
Allow users to set the sort order in the UI

### ISSUE THREAD

**Issue by EmilStenstrom** [EmilStenstrom/mybgg#25]
Feature idea: Set sorting in UI fx http://u.lillefar.dk/tYyohV

_Originally posted by @lajlev in https://github.com/EmilStenstrom/mybgg/issues/23#issuecomment-460184089_

**Comment by Medwynd** [comment]
This would be a nice addition

**Comment by EmilStenstrom** [comment]
ping @lajlev @Medwynd - This is now possible thanks to a contribution by @MichaelThomasMPT!
