### ISSUE TITLE
Moving filters back to the right side

### ISSUE THREAD

**Issue by Medwynd** [EmilStenstrom/mybgg#28]
The current filters at the top of the screen are difficult to use on Android with Firefox.  You have to drag your thumb over the filters because they dont all appear at once.  The previous way they were all at your fingertips to pick and choose easily.  Is there a setting to change this back or should I roll back to that version to get that functionality restored?

**Comment by EmilStenstrom** [comment]
There's no setting to change this back either. The main reason this was changed was to give more space to the games. This is especially true for mobile, where the filters took up much of the screen.

Yes, rolling back will also change this back to how it was before.
