### ISSUE TITLE
Updating collection

### ISSUE THREAD

**Issue by danishbuddha** [EmilStenstrom/mybgg#4]
I updated my bgg collection, but it still pull the old list before updating. I asume that is a cache issue somewhere, but is it possible to make it update itself somehow?

**Comment by kelleyaj** [comment]
I had to delete the mybgg-cache.sqlite file that was created to get it to update.  Would be nice if there was a param to pass in to do that or update the db cahce.

**Comment by EmilStenstrom** [comment]
Good suggestion. I’ve already decreased the number of requests made each time you fetch to two requests, so maybe I should just remove the cache altogether...

**Comment by EmilStenstrom** [comment]
I've removed the cache altogether. One less thing to worry about :)
