### ISSUE TITLE
Feature Request: Add a filter-by-minimum-recommended-age (listed, community)

### ISSUE THREAD

**Issue by calibandotexe** [EmilStenstrom/mybgg#47]
BGG advanced search ([https://boardgamegeek.com/advsearch/boardgame]) includes a minimum-age option, which returns titles at the listed minimum _(i.e. 8+)_. Looking at a game detail page, it appears that there's a community-recommended minimum as well.

As someone in a tabletop family with younger nieces and nephews, I'd like to be able to quickly suggest titles from my collection that would be easier to start with.

**Comment by EmilStenstrom** [comment]
Great suggestion! I can't promise I have time to look at this any time soon, but I'll keep this open and we'll see if some time arises!

**Comment by EmilStenstrom** [comment]
This is now implemented. I did the simplest thing I could think of. Just the official age, and allowed filters for < 5, 7, 9, 11, 13, 15. Let me know how this works for you.

**Comment by calibandotexe** [comment]
I think this will definitely help! Thank you for adding this feature @EmilStenstrom!
