### ISSUE TITLE
Ability to include expansions?

### ISSUE THREAD

**Issue by kelleyaj** [EmilStenstrom/mybgg#5]
I wanted to include the expansions I have for games in the returned collection.  But after trying to configure the config boardgamegeek object i wasn't able to figure out where to add it.  Looking at the API page - https://lcosmin.github.io/boardgamegeek/modules.html#boardgamegeek.api.BGGClient.collection - it looks like it should be possible via subtype, but i could not get a successful call with the subtype attribute.

```  
  "boardgamegeek": {
        "user_name": "####",
        "subtype": "boardgame,boardgameexpansion",
        "extra_params": {
            "own": 1
        }
    },
```

**Comment by EmilStenstrom** [comment]
Hi @kelleyaj! Great suggestion. I had hardcoded the removal of all expansions, since I only wanted games... I just moved that to the config file instead, so you can just remove that part and expansions should be automatically included. Does that work for you?

Here are the code changes that make this possible: https://github.com/EmilStenstrom/mybgg/commit/c6ef7a87974c6e79db187f766592508f7d6dc416

**Comment by kelleyaj** [comment]
That works thanks!  But maybe we should add a filter to the right side bar to show or hide expansions?  I can look into that, or if you know what file to point me to.

**Comment by EmilStenstrom** [comment]
I think most people won't want expansions at all (use-case is (i think) picking a game for the game night), so they will just have it excluded using the settings in config.json. The use-case for filtering is if you sometimes want expansions, and sometimes not. Is that why you want the filter?

**Comment by kelleyaj** [comment]
@EmilStenstrom yes that is the use case.  It can be taken a little further to add more value as most of my expansions add the ability to play with more players.  So when planning a game night the group would need to know if I have the expansion or not to know how many players we could have.  So if would be great to be able to have expansions be there and filtered out by default, but have the ability to show the expansions for that purpose.  Does that make sense?

**Comment by EmilStenstrom** [comment]
I wonder, how are the expansions categorized? If the base game is four players, and an expansions adds a fifth, does only the expansion show up when you filter for five players? Or is the base game categorized as supporting five players since there's an expansion you _could_ have?

Another option I see is to add expansions, and connect them to each game in the filtering/search. So each game would be categorized as the maximum number of players any of your expansions have?

**Comment by kelleyaj** [comment]
> If the base game is four players, and an expansions adds a fifth, does only the expansion show up when you filter for five players?

Yes this is the case.  For example I have Catan which is up to 4 players, and I then have the 5-6 player expansion.  When filtering for number of players 5 or more only the Catan expansion is shown.

> Another option I see is to add expansions, and connect them to each game in the filtering/search. So each game would be categorized as the maximum number of players any of your expansions have?

I think this is a good idea, if it would be possible to denote if the user has the expansion with the base game and then merge that number of players and/or other data fields it would make it pretty seamless.

**Comment by EmilStenstrom** [comment]
Excellent, I see how this would be useful for me too. I'll see if I can get it working, but it might take a little while, because this is a bigger change.

**Comment by kelleyaj** [comment]
Awesome.  Let me know if there is anything I can help out on.

**Comment by EmilStenstrom** [comment]
Hi again! I think I got everything working like you suggested. You can see it working here: https://games.emilstenstrom.se/?query=Carcassonne (which adds a fifth player with expansions)

* Clicking a number of players only available through an expansion which you own (six for Carcassonne), shows the base game in results
* There's a new suboption in the num player facet that allows for filtering on only games that where more players where added by an expansion
* When expanding a game the list of player numbers show which one requires an expansion.

I decided that I didn't need to connect the specific expansion that allows for more players, that the owner of the games probably already knows that.

How does that work for you?

**Comment by kelleyaj** [comment]
This is great, thank you for getting this in @EmilStenstrom 🥇
