### ISSUE TITLE
BGG throttling the public API?

### ISSUE THREAD

**Issue by Kornstalx** [EmilStenstrom/mybgg#56]
Haven't updated my library in a while. Just tried earlier (once) and the script was kicking back an HTTP 429.
Heading directly to the link shows some sort of throttling enabled. I've used mybgg for years and never seen this one:

I'll try again tomorrow to manually hit the link and see if it works. If it does, I'll try the script again and see if it is triggering the throttle. 

![chrome_2022-07-17_01-51-01](https://user-images.githubusercontent.com/18632150/179387557-adbe9518-26fb-421d-ad00-24fd20a2e940.png)
.

**Comment by EmilStenstrom** [comment]
Yeah, that happens. It's not a change with mybgg, but something with the API. Retrying after a few seconds usually works.

**Comment by Kornstalx** [comment]
Yep, that's all it was. Working fine today. Closing this.
Thank you!
