### ISSUE TITLE
Ability to include pre-ordered and want to buy?

### ISSUE THREAD

**Issue by sgall23** [EmilStenstrom/mybgg#8]
This is probably only really specific to me, but I wanted to use this so my group and I can keep track of the games we have pre-ordered and what games we're interested in getting as well. How would I go about adding those options? I don't have much experience or skill with this stuff, so I don't really know where to even begin.

**Comment by EmilStenstrom** [comment]
Hi! I see two different feature requests here:

1. You want to filter games that are preordered.
2. You want to filter games that are on your wishlist
3. You want to add games from more than one user's collection

Which one of them would you need? All three of them?

**Comment by EmilStenstrom** [comment]
I see! I saw your commits to your project, and you are on the right track. The problem is that the parameters in config.json are all applied simultaneously. So you tried filtering on games you both own, have preordered, and are on your wishlist. I think you might get what you want by first just setting `preorder: 1` (and none of the other ones), run the script, and then only `want_to_buy: 1`, and run the script again (no need to commit those changes, you run the script locally anyway). 

Of course, that means you wouldn't be able to see which games come from want to buy list, and which ones are preordered...

**Comment by sgall23** [comment]
Oh awesome, I got that to work! I just had to run the script a couple of times for it to go succeed. 

Is there a way I could add a new filter so we could filter between own, preordered, and want to buy when we look?

**Comment by EmilStenstrom** [comment]
Ah, didn't remember I added deletion too. It's needed so you can remove a game from BGG, and have it removed from your site too.

So instead, I've added a new way to configure the search parameters in the latest version (be sure to update first!). Try this:

`"extra_params": [{"preorder": 1}, {"want_to_buy": 1}]`

Specifying a list to extra_params like this means "give me games that are preordered OR want_to_buy". Hope this will work for you!

**Comment by sgall23** [comment]
Thank you so much for the new additions to help this along, I really appreciate it!

Since I'm kinda dumb with this stuff, how should config.json look with `"extra_params": [{"preorder": 1}, {"want_to_buy": 1}]` added? I'm not exactly sure where to put it.

**Comment by EmilStenstrom** [comment]
Oh, great question, sorry for being vague:

The default config.json looks like this:

```json
{
    "project": {
        "name": "mybgg",
        "title": ""
    },
    "boardgamegeek": {
        "user_name": "YOUR_BGG_USERNAME",
        "extra_params": {
            "own": 1
        }
    },
    "algolia": {
        "app_id": "YOUR_APP_ID",
        "api_key_search_only": "YOUR_PUBLIC_API_KEY",
        "index_name": "YOUR_INDEX_NAME"
    }
}
```

My suggestion is to change the dictionary (that's the thing between { and } inside extra_params, so the end results looks like this instead:

```json
{
    "project": {
        "name": "mybgg",
        "title": ""
    },
    "boardgamegeek": {
        "user_name": "YOUR_BGG_USERNAME",
        "extra_params": [
            {"own": 1},
            {"preorder": 1},
            {"want_to_buy": 1}
        ]
    },
    "algolia": {
        "app_id": "YOUR_APP_ID",
        "api_key_search_only": "YOUR_PUBLIC_API_KEY",
        "index_name": "YOUR_INDEX_NAME"
    }
}
```

**Comment by sgall23** [comment]
No worries, not your fault I have no clue what I'm doing. haha

But it worked perfectly. Thank you again for all your help!
